version: '3.8'

services:
  # Backend Flask + SocketIO
  backend:
    build: .
    container_name: guiaipn-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=True
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - guiaipn-network
    restart: unless-stopped

  # Redis para cache y sesiones
  redis:
    image: redis:7-alpine
    container_name: guiaipn-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - guiaipn-network
    restart: unless-stopped
    command: redis-server --appendonly yes

networks:
  guiaipn-network:
    driver: bridge

volumes:
  redis-data:
